SELECT TABLE WALMART_OPERATIONS (
	STORE NUMBER(38,0),
	REGION VARCHAR(20),
	OPERATIONS_COSTS NUMBER(38,0),
	HIRE_RATE NUMBER(10,2)
	primary key (STORE),
	foriegn key (STORE) references OPENAI.KAGGLE.WALMART.STORE(STORE)
);